<#
.SYNOPSIS
    Installs the complete FORTIQ Windows product.
.DESCRIPTION
    Shared engine for the role-specific Setup executables. The role is explicit,
    and Client installation is rejected without a valid Operator PeerId.
#>
[CmdletBinding()]
param (
    [Parameter(Mandatory = $true)]
    [ValidateSet("Operator", "Client")]
    [string]$Role,
    [string]$OperatorPeerId,
    [string]$NodeName = $env:COMPUTERNAME,
    [switch]$ForceRoleChange
)

$ErrorActionPreference = "Stop"
$ServiceName = "FortiqService"
$InstallDir = "C:\Program Files\FORTIQ"
$DataDir = "C:\ProgramData\FORTIQ"
$ConfigFile = Join-Path $DataDir "fortiq.toml"
$RunKeyPath = "Software\Microsoft\Windows\CurrentVersion\Run"
$RunValueName = "FORTIQ Desktop"

function Test-Administrator {
    $principal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    return $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

function Test-OperatorPeerId([string]$PeerId) {
    if ([string]::IsNullOrWhiteSpace($PeerId)) { return $false }
    return $PeerId -match '^12D3KooW[1-9A-HJ-NP-Za-km-z]{40,60}$'
}

function Get-InstalledRole([string]$Path) {
    if (-not (Test-Path -LiteralPath $Path)) { return $null }
    if ((Get-Content -Raw -LiteralPath $Path) -match '(?m)^\s*operator_peer_id\s*=') { return "Client" }
    return "Operator"
}

if (-not (Test-Administrator)) {
    throw "FORTIQ installation requires Administrator privileges. Run the role-specific Setup executable."
}
if ([string]::IsNullOrWhiteSpace($NodeName) -or $NodeName.IndexOfAny([char[]]"`"`r`n") -ge 0) {
    throw "NodeName is empty or contains unsupported characters."
}
if ($Role -eq "Client" -and -not (Test-OperatorPeerId $OperatorPeerId)) {
    throw "Client installation requires a valid Operator PeerId (12D3KooW...)."
}

$existingRole = Get-InstalledRole $ConfigFile
if ($existingRole -and $existingRole -ne $Role -and -not $ForceRoleChange) {
    throw "Existing role is $existingRole. Refusing to change to $Role without -ForceRoleChange."
}

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Definition
$requiredFiles = @("fortiq-service.exe", "fortiq.exe", "fortiq-desktop.exe", "uninstall.ps1")
foreach ($file in $requiredFiles) {
    if (-not (Test-Path -LiteralPath (Join-Path $scriptDir $file))) {
        throw "Incomplete FORTIQ package: required file '$file' is missing."
    }
}

Write-Host "Installing FORTIQ $Role on $NodeName..." -ForegroundColor Cyan
if (Get-Service -Name $ServiceName -ErrorAction SilentlyContinue) {
    Stop-Service -Name $ServiceName -Force -ErrorAction SilentlyContinue
    if (Test-Path -LiteralPath (Join-Path $InstallDir "fortiq-service.exe")) {
        & (Join-Path $InstallDir "fortiq-service.exe") service uninstall | Out-Null
    }
}
Get-Process -Name "fortiq-desktop", "FORTIQ" -ErrorAction SilentlyContinue |
    Stop-Process -Force -ErrorAction SilentlyContinue

New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
New-Item -ItemType Directory -Path $DataDir -Force | Out-Null
foreach ($file in $requiredFiles + @("install.ps1")) {
    $source = Join-Path $scriptDir $file
    if (Test-Path -LiteralPath $source) {
        $destination = Join-Path $InstallDir $file
        if ([IO.Path]::GetFullPath($source) -ne [IO.Path]::GetFullPath($destination)) {
            Copy-Item -LiteralPath $source -Destination $destination -Force
        }
    }
}

$authorization = if ($Role -eq "Client") {
    "[authorization]`r`noperator_peer_id = `"$OperatorPeerId`"`r`n"
} else {
    "# Operator role: operator_peer_id is intentionally absent.`r`n[authorization]`r`n"
}
$config = @"
# Generated by FORTIQ $Role Setup. Role changes require explicit confirmation.
[node]
name = "$NodeName"

[identity]
path = "C:/ProgramData/FORTIQ/identity.key"

$authorization
[network]
listen_quic = "0.0.0.0:4001"
relay_peer = "/ip4/51.255.46.58/udp/4001/quic-v1/p2p/12D3KooWRFrWVx2CANXcjXvTNaqkh6APgAecsW94CLwNEg5wsqLy"

[ticket]
path = "C:/ProgramData/FORTIQ/ticket.json"
"@
Set-Content -LiteralPath $ConfigFile -Value $config -Encoding utf8

$machinePath = [Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine)
$pathEntries = @($machinePath -split ';' | Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
if ($pathEntries -notcontains $InstallDir) {
    [Environment]::SetEnvironmentVariable("Path", (($pathEntries + $InstallDir) -join ';'), [EnvironmentVariableTarget]::Machine)
}
$env:Path = "$env:Path;$InstallDir"

& (Join-Path $InstallDir "fortiq-service.exe") service install --config $ConfigFile
& (Join-Path $InstallDir "fortiq-service.exe") service start

# Use the 64-bit registry view explicitly: the NSIS bootstrapper is 32-bit and
# otherwise redirects this value to WOW6432Node, which Windows does not use for
# normal desktop logon startup.
$registryBase = [Microsoft.Win32.RegistryKey]::OpenBaseKey(
    [Microsoft.Win32.RegistryHive]::LocalMachine,
    [Microsoft.Win32.RegistryView]::Registry64
)
$runKey = $registryBase.CreateSubKey($RunKeyPath)
try {
    $runKey.SetValue($RunValueName, ('"{0}"' -f (Join-Path $InstallDir "fortiq-desktop.exe")), [Microsoft.Win32.RegistryValueKind]::String)
} finally {
    $runKey.Dispose()
    $registryBase.Dispose()
}
# Remove the incorrectly redirected value left by pre-fix installers.
$legacyRegistryBase = [Microsoft.Win32.RegistryKey]::OpenBaseKey(
    [Microsoft.Win32.RegistryHive]::LocalMachine,
    [Microsoft.Win32.RegistryView]::Registry32
)
$legacyRunKey = $legacyRegistryBase.OpenSubKey($RunKeyPath, $true)
if ($legacyRunKey) {
    try { $legacyRunKey.DeleteValue($RunValueName, $false) } finally { $legacyRunKey.Dispose() }
}
$legacyRegistryBase.Dispose()

$startMenuDir = Join-Path $env:ProgramData "Microsoft\Windows\Start Menu\Programs\FORTIQ"
New-Item -ItemType Directory -Path $startMenuDir -Force | Out-Null
$shell = New-Object -ComObject WScript.Shell
$desktopShortcut = $shell.CreateShortcut((Join-Path $startMenuDir "FORTIQ.lnk"))
$desktopShortcut.TargetPath = Join-Path $InstallDir "fortiq-desktop.exe"
$desktopShortcut.WorkingDirectory = $InstallDir
$desktopShortcut.Description = "FORTIQ $Role"
$desktopShortcut.Save()
$cliShortcut = $shell.CreateShortcut((Join-Path $startMenuDir "FORTIQ CLI.lnk"))
$cliShortcut.TargetPath = "powershell.exe"
$cliShortcut.Arguments = '-NoExit -Command "fortiq status"'
$cliShortcut.WorkingDirectory = $InstallDir
$cliShortcut.Description = "FORTIQ command line"
$cliShortcut.Save()

Write-Host "FORTIQ $Role installation completed." -ForegroundColor Green
Write-Host "Service starts at boot; desktop starts at interactive user logon."
& (Join-Path $InstallDir "fortiq.exe") status
