<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Fortiq.Infrastructure.Keys\Fortiq.Infrastructure.Keys.csproj" />
    <ProjectReference Include="..\Fortiq.Infrastructure.Restic\Fortiq.Infrastructure.Restic.csproj" />
    <ProjectReference Include="..\Fortiq.PasswordHelper\Fortiq.PasswordHelper.csproj" />
    <ProjectReference Include="..\Fortiq.Infrastructure.ObjectStorage\Fortiq.Infrastructure.ObjectStorage.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
