[package]
name = "fortiq-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
fortiq-core = { path = "../fortiq-core" }
fortiq-shell = { path = "../fortiq-shell" }
futures.workspace = true
libp2p.workspace = true
libp2p-stream.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio-util = { workspace = true, features = ["compat"] }
tracing-subscriber = { workspace = true }
