<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Xunit.SkippableFact" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Fortiq.Recover\Fortiq.Recover.csproj" />
    <ProjectReference Include="..\..\src\Fortiq.Application\Fortiq.Application.csproj" />
    <ProjectReference Include="..\..\src\Fortiq.Infrastructure.Restic\Fortiq.Infrastructure.Restic.csproj" />
    <ProjectReference Include="..\..\src\Fortiq.Infrastructure.Keys\Fortiq.Infrastructure.Keys.csproj" />
    <ProjectReference Include="..\..\src\Fortiq.PasswordHelper\Fortiq.PasswordHelper.csproj" />
    <ProjectReference Include="..\..\src\Fortiq.Infrastructure.Receipts\Fortiq.Infrastructure.Receipts.csproj" />
    <ProjectReference Include="..\..\src\Fortiq.Provisioning\Fortiq.Provisioning.csproj" />
  </ItemGroup>

</Project>